version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
      - source: index_html
        target: /usr/share/nginx/html/index.html

configs:
  nginx_conf:
    content: |
      limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;
      limit_conn_zone $binary_remote_addr zone=addr:10m;

      server {
          listen 80;
          server_name authentication.social;

          root /usr/share/nginx/html;
          index index.html;

          # Security headers
          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-XSS-Protection "1; mode=block" always;
          add_header X-Content-Type-Options "nosniff" always;

          # Cache and DDoS protection
          location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
              expires 30d;
              add_header Cache-Control "public, no-transform";
          }

          limit_req zone=one burst=10 nodelay;
          limit_conn addr 10;

          location / {
              try_files $uri $uri/ =404;
              client_body_timeout 10s;
              client_header_timeout 10s;
          }
      }

  index_html:
    content: |
      <!DOCTYPE html>
      <html>
        <head>
          <title>Welcome</title>
        </head>
        <body>
          <h1>Welcome to authentication.social</h1>
        </body>
      </html>
