version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
      - source: index_html
        target: /usr/share/nginx/html/index.html

configs:
  nginx_conf:
    content: |
      limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

      server {
          listen 80;
          server_name authentication.social;

          root /usr/share/nginx/html;
          index index.html;

          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-XSS-Protection "1; mode=block" always;
          add_header X-Content-Type-Options "nosniff" always;

          location / {
              limit_req zone=mylimit burst=10;
              try_files $uri $uri/ =404;
              client_body_timeout 10s;
              client_header_timeout 10s;
          }
      }

  index_html:
    content: |
      <!DOCTYPE html>
      <html>
        <head>
          <title>Welcome</title>
        </head>
        <body>
          <h1>Welcome to authentication.social</h1>
        </body>
      </html>
